# Generated by Django 6.0.6 on 2026-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=1000)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
